# -*- coding: utf-8 -*-
"""data_quality_check

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bjc2oeOybsGvcWj9SZYu3Vgp8pDrqmKy
"""

import pandas as pd
import yfinance as yf
import numpy as np

TEST_TICKERS = ['AC.PA', 'BNP.PA', 'MC.PA', 'OR.PA', 'TTE.PA']

def check_and_clean_data(df):
    """
    Analyse la qualité des données financières et nettoie les valeurs manquantes.
    """
    print(f"\n{'='*40}")
    print("RAPPORT DE QUALITÉ DES DONNÉES (DATA CLEANING)")
    print(f"{'='*40}")

    rows, cols = df.shape
    print(f"Dimensions du dataset : {rows} jours x {cols} actions")

    missing_values = df.isnull().sum().sum()
    print(f"Total valeurs manquantes : {missing_values}")

    if missing_values > 0:
        print("Détail par action :")
        print(df.isnull().sum()[df.isnull().sum() > 0])
    else:
        print("Aucune valeur manquante détectée (Dataset complet).")

    duplicates = df.index.duplicated().sum()
    print(f"Lignes dupliquées : {duplicates}")


    print("\nApplication du nettoyage (Fill Method: Forward Fill)...")
    df_clean = df.ffill().bfill()

    remaining_missing = df_clean.isnull().sum().sum()
    print(f"Valeurs manquantes après nettoyage : {remaining_missing}")

    return df_clean

if __name__ == "__main__":
    print("Téléchargement d'un échantillon de données réelles...")
    data = yf.download(TEST_TICKERS, period="6mo", progress=False, auto_adjust=True)['Close']

    # On simule une erreur
    data.iloc[5, 0] = np.nan
    data.iloc[10, 2] = np.nan


    clean_data = check_and_clean_data(data)
    print("\nsuccès : Le module de nettoyage est opérationnel.")